export const GET_LAUNCHES = 'GET_LAUNCHES';
export const GET_LAUNCHES_SUCCESS = 'GET_LAUNCHES_SUCCESS';
export const GET_LAUNCHES_FAILED = 'GET_LAUNCHES_FAILED';
export const SET_ERROR = 'SET_ERROR';
export const SET_IS_LOADED = 'SET_IS_LOADED';
export const SET_NAVIGATION = 'SET_NAVIGATION';
